
project_id = "zmcmrivswbszhqqragli"

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = true

[functions.text-to-voice]
verify_jwt = true
