
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Handle single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  publish = "dist"
  autoLaunch = true
  framework = "vite"
